"use client"
import { AuthProvider } from "@/auth/authProvider"
import { initializeFirebaseApp } from "@/lib/firebase"
import { ChakraProvider } from "@chakra-ui/react"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
initializeFirebaseApp()
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
